sonar.projectKey=gocore
sonar.projectName=gocore

sonar.sources=pkg
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/testdata/**,**/*.pb.go,**/*_gen.go,bin/**,.worktrees/**

sonar.go.file.suffixes=.go
sonar.sourceEncoding=UTF-8
